name: LastManStanding
main: no.runsafe.lastmanstanding.LastManStanding
version: 1.0.@BUILD@
author: Kruithne
description: Last Man Standing mini-game.
commands:
  lms:
    description: Last Man Standing commands
